% simpleMPC_solver - a fast optimizer generated by FORCES Pro through Y2F
%
%   OUTPUT = simpleMPC_solver(PARAMS) solves a multistage problem
%   subject to the parameters supplied in a cell array with the following elements:
%       PARAMS{1} is inputvariables (column vector of length 11)
%
%   OUTPUT is a cell array containg the values of the last iteration of the solver where
%       OUTPUT{1} is u0_variable (column vector of length 4)
%
%   [OUTPUT, EXITFLAG] = simpleMPC_solver(PARAMS) returns additionally
%   the integer EXITFLAG indicating the state of the solution with 
%       1 - OPTIMAL solution has been found (subject to desired accuracy)
%       0 - Timeout - maximum number of iterations reached
%      -7 - Method could not progress. Problem may be infeasible.
%    -100 - License error
%
%   [OUTPUT, EXITFLAG, INFO] = simpleMPC_solver(PARAMS) returns 
%   additional information about the last iterate:
%       INFO.it        - number of iterations that lead to this result
%       INFO.res_eq    - max. equality constraint residual
%       INFO.res_ineq  - max. inequality constraint residual
%       INFO.pobj      - primal objective
%       INFO.dobj      - dual objective
%       INFO.dgap      - duality gap := pobj - dobj
%       INFO.rdgap     - relative duality gap := |dgap / pobj|
%       INFO.mu        - duality measure
%       INFO.sigma     - centering parameter
%       INFO.lsit_aff  - iterations of affine line search
%       INFO.lsit_cc   - iterations of line search (combined direction)
%       INFO.step_aff  - step size (affine direction)
%       INFO.step_cc   - step size (centering direction)
%       INFO.solvetime - Time needed for solve (wall clock time)
%
% See also COPYING