/*
 This is an interface for simpleMPC_solver that can be used to call the solver generated by FORCES Pro
*/ 

#include "../include/simpleMPC_solver.h"
#include "../include/internal_simpleMPC_solver_1.h"
#include <stdio.h>

/* Some memory */
internal_simpleMPC_solver_1_params params_1;
internal_simpleMPC_solver_1_output output_1;
internal_simpleMPC_solver_1_info info_1;

int exitflag;
int simpleMPC_solver_solve(simpleMPC_solver_params* params, simpleMPC_solver_output* output, simpleMPC_solver_info* info, FILE* fs) {
	/* define variables */
	int i;
	/* SOLVER 1 --------------------------------------------------------*/
	/*Assigning parameter values of solver #1*/
	/*Assigning parameter values of solver #1*/
	params_1.p_1[0] = 1 * params->inputvariables[8];

	params_1.p_2[0] = 0;
	params_1.p_2[1] = 0;
	params_1.p_2[2] = 1 * params->inputvariables[1];
	params_1.p_2[3] = 1 * params->inputvariables[4];
	params_1.p_2[4] = 0;
	params_1.p_2[5] = 0;
	params_1.p_2[6] = 0;
	params_1.p_2[7] = 0;
	params_1.p_2[8] = 0;
	params_1.p_2[9] = 0;
	params_1.p_2[10] = 0;
	params_1.p_2[11] = 0;
	params_1.p_2[12] = 0;
	params_1.p_2[13] = 0;

	params_1.p_3[0] = 1 * params->inputvariables[7];
	params_1.p_3[1] = 0;
	params_1.p_3[2] = 0;
	params_1.p_3[3] = 0;
	params_1.p_3[4] = 0;
	params_1.p_3[5] = 1 * params->inputvariables[0];
	params_1.p_3[6] = 1 * params->inputvariables[6];
	params_1.p_3[7] = 0;
	params_1.p_3[8] = 0;
	params_1.p_3[9] = 0;
	params_1.p_3[10] = 0;
	params_1.p_3[11] = 0;
	params_1.p_3[12] = 0;
	params_1.p_3[13] = 0;
	params_1.p_3[14] = 0;
	params_1.p_3[15] = 0;
	params_1.p_3[16] = 0;
	params_1.p_3[17] = 0;
	params_1.p_3[18] = 0;
	params_1.p_3[19] = 0;
	params_1.p_3[20] = 0;
	params_1.p_3[21] = 0;
	params_1.p_3[22] = 0;
	params_1.p_3[23] = 0;

	params_1.p_4[0] = 1 * params->inputvariables[9];
	params_1.p_4[1] = 1 * params->inputvariables[10];
	params_1.p_4[2] = 0;
	params_1.p_4[3] = 1 * params->inputvariables[2];
	params_1.p_4[4] = 1 * params->inputvariables[3];
	params_1.p_4[5] = 1 * params->inputvariables[5];
	params_1.p_4[6] = 0;
	params_1.p_4[7] = 0;
	params_1.p_4[8] = 0;
	params_1.p_4[9] = 0;
	params_1.p_4[10] = 0;
	params_1.p_4[11] = 0;
	params_1.p_4[12] = 0;
	params_1.p_4[13] = 0;
	params_1.p_4[14] = 0;
	params_1.p_4[15] = 0;
	params_1.p_4[16] = 0;
	params_1.p_4[17] = 0;

	/* call solver #1 */
	exitflag = internal_simpleMPC_solver_1_solve(&params_1, &output_1, &info_1, fs );

	/* iterations */
	info->it = info_1.it;

	/* iterations to optimality (branch and bound) */
	info->it2opt = info_1.it2opt;

	/* res_eq */
	info->res_eq = info_1.res_eq;

	/* res_ineq */
	info->res_ineq = info_1.res_ineq;

	/* pobj */
	info->pobj = info_1.pobj;

	/* dobj */
	info->dobj = info_1.dobj;

	/* dgap */
	info->dgap = info_1.dgap;

	/* rdgap */
	info->rdgap = info_1.rdgap;

	/* mu */
	info->mu = info_1.mu;

	/* mu_aff */
	info->mu_aff = info_1.mu_aff;

	/* sigma */
	info->sigma = info_1.sigma;

	/* lsit_aff */

	info->lsit_aff = info_1.lsit_aff;

	/* lsit_cc */
	info->lsit_cc = info_1.lsit_cc;

	/* step_aff */
	info->step_aff = info_1.step_aff;

	/* step_cc */
	info->step_cc = info_1.step_cc;

	/* solver time */
	info->solvetime = info_1.solvetime;


	/* OUTPUTS -----------------------------------------------------------*/
	/*Build outputs*/
	output->u0_variable[0] = 0 + 1 * output_1.o_1[0];


	output->u0_variable[1] = 0 + 1 * output_1.o_2[0];


	output->u0_variable[2] = 0 + 1 * output_1.o_3[0];


	output->u0_variable[3] = 0 + 1 * output_1.o_4[0];


	return exitflag;
}